### ISSUE TITLE
Support v3 API

### ISSUE THREAD

**Issue by jmckible** [kaushiksv/omniauth-surveymonkey#4]
Hi Kaushik,

My name is Jordan McKible. I work for SurveyMonkey. We would like to release and support an official omniauth plugin for our API. We have recently release v3 and it appears this library is no longer compatible. Since you are the owner of the gem, would you have any interest in turning over control to us, or merging in our repo?

Thanks.

https://github.com/techvalidate/omniauth-surveymonkey

**Comment by kaushiksv** [comment]
Hi Jordan,

I will transfer the ownership of gem. Could you please send me an e-mail from @surveymonkey.com domain?

Also, please let me know the e-mail address to be used in `gem owner` command. 

Thanks.

Br
Kaushik
